resources:
  - name: test
    type: gitRepo
    repoPath: vijayreddy1991/resourcebashpipeline
    configuration:
      integrationName: github_vijay
      branches:
        only: master
    version:
      sha: master

pipelines:
  - name: pipe_steps
    steps:
      - name: step_state
        type: bash
        setup:
          runtime:            
            type: image
            image:
              auto:
                language: nodejs
                versions: 
                  - 10.15.3
              custom:
                name: drydock/u16node
                tag: master
                options: ""
        triggeredBy:
          resources:
            - test
        execution:
          onStart:
            - printenv
          onExecute:
            - printenv
            - echo "vijay" 
            - bump_semver v1.0.0 patch

#   - name: runtime
#     setup: 
# #       environmentVariables:
# #         readOnly:
# #           Number: 27   
#       runtime:       
#         type: 
#         image:
#           auto:
#             language: nodejs
#             versions:
#               - 10.15.3
# #           custom:
# #             name: "drydock/u16node"
# #             tag: "master"
# #             options: "--env VIJAY=kumar"
#     steps:    
#       - name: test1
#         type: bash
#         setup:
#           environmentVariables:
#             normal:
#              Number: 27         
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16node
#                tag: master
#         triggeredBy:
#            resources:
#               - test
#         execution:
#           onExecute:
#             - echo "hi"
#             - printenv
#             - add_run_variable vijay=kumar

#       - name: test2
#         type: bash   
#         triggeredBy:
#           steps:
#             - test1
#         execution:
#           onExecute:
#             - echo "test2"
#             - echo $vijay
#             - echo $Number

#       - name: test3
#         type: bash  
#         triggeredBy:
#           steps:
#             - test2
#         execution:
#           onExecute:
#             - echo "Test3"
#             - echo $vijay

# #       - name: test4
# #         type: bash   
# #         execution:
# #           onExecute:
# #             - echo "test4"
# #             - echo $FOO_STATE

#   - name: pipeline1234
#     steps:
#       - name: testbash1
#         type: bash
#         configuration:
#           affinityGroup: vijay@#$%^&*
# #           priority: 3
# #           timeoutSeconds: <job timeout limit>
#           nodePool: kermit_ubuntu_pool
#           chronological: false       
#         setup:
# #           environmentVariables:
# #             normal:
# #               vijay: kumar  
#           runtime:            
#             type: image
#             image:
#               auto:
#                 language: nodejs
#                 versions: 
#                   - 8.16.0
#               custom:
#                 name: drydock/c7node
#                 tag: master
#                 options: ""
#         triggeredBy:
#           resources:
#             - test
#         execution:
#           onStart:
#             - printenv
#           onExecute:
# #             - test "$vijay" == "kumar"
#             - printenv
#             - echo "vijay"
# #           onSuccess:
# # #             - test "$ENV1" == "value1"
# #               - printenv
# #           onFailure:
# #            - printenv
# #           onComplete: #always
# #             - test "$vijay" == "kumar"
# #             - printenv
# #           onCancel:
# #             - test "$ENV1" == "value1"
# #             - test "$SECURE_ENV" == "key"

#       - name: testbash2
#         type: bash
#         configuration:
#           affinityGroup: vijay@#$%^&*
#           priority: 2
# #           timeoutSeconds: <job timeout limit>
#           nodePool: kermit_ubuntu_pool
#           chronological: false
#         setup:
# #           environmentVariables:
# #             normal:
# #               ENV1: value1
# #               ENV2: value2
# #             encrypted:
# #               SECURE_ENV1: <encrypted secure>
# #               SECURE_ENV2: <encrypted secure>
#           runtime:            
#             type: image
#             image:
#               auto:
#                 language: nodejs
#                 versions: 
#                   - 10.15.3
#               custom:
#                 name: drydock/u16node
#                 tag: master
#                 options: ""
#         triggeredBy:
#           steps:
#             - testbash1
#         execution:
#           onStart:
#             - printenv
#           onExecute:
# #             - test "$vijay" == "kumar"
#             - printenv
#             - echo "vijay"
# #           onSuccess:
# # #             - test "$ENV1" == "value1"
# #               - printenv
# #           onFailure:
# #            - printenv
# #           onComplete: #always
# #             - test "$vijay" == "kumar"
# #             - printenv
# #           onCancel:
# #             - test "$ENV1" == "value1"
# #             - test "$SECURE_ENV" == "key"
            

#       - name: testbash3
#         type: bash
#         configuration:
#           affinityGroup: vijay@#$%^&*
#           priority: 1
# #           timeoutSeconds: <job timeout limit>
#           nodePool: kermit_ubuntu_pool
#           chronological: false        
#         setup:
# #           environmentVariables:
# #             normal:
# #               vijay: kumar  
#           runtime:            
#             type: image
#             image:
#               auto:
#                 language: nodejs
#                 versions: 
#                   - 8.16.0
#               custom:
#                 name: drydock/u16node
#                 tag: master
#                 options: ""
#         triggeredBy:
#           steps:
#             - testbash2
#         execution:
#           onStart:
#             - printenv
#           onExecute:
# #             - test "$vijay" == "kumar"
#             - printenv
#             - echo "vijay"
# #           onSuccess:
# # #             - test "$ENV1" == "value1"
# #               - printenv
# #           onFailure:
# #            - printenv
# #           onComplete: #always
# # #             - test "$vijay" == "kumar"
# #             - printenv
# #           onCancel:
# # #             - test "$ENV1" == "value1"
# # #             - test "$SECURE_ENV" == "key"
# #               - printenv

  
#   - name: pipeline
#     setup:
#       environmentVariables:
#         readOnly:
#           NameF: vijay
#           NameL: kumar
#     steps:    
#       - name: test1
#         type: bash
#         setup:
#           environmentVariables:
#             readOnly:
#               NameF: reddy
#               NameL: umar       
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16all
#                tag: master
#         triggeredBy:
#           resources:
#             - test
#         execution:
#           onExecute:
#             - echo "test1"
#             - echo "NameL=$NameL"
#             - echo "NameF=$NameF"

#       - name: test2
#         type: bash
#         setup:
#           environmentVariables:
#             readOnly:
#               NameF: ranjan
#               NameL: bindu        
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16all
#                tag: master
#         triggeredBy:
#           steps:
#             - test1
#         execution:
#           onExecute:
#             - echo "test2"
#             - echo "NameF=$NameF"
#             - echo "NameL=$NameL"

#       - name: test3
#         type: bash
#         setup:
#           environmentVariables:
#             readOnly:
#               NameF: barath
#               NameL: jatin     
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16all
#                tag: master
#         triggeredBy:
#           steps:
#             - test2
#         execution:
#           onExecute:
#             - echo "Test3"
#             - echo "NameF=$NameF"
#             - echo "NameL=$NameL"

#       - name: test4
#         type: bash
#         setup:
#           environmentVariables:
#             readOnly:
#               NameF: Chaitu
#               NameL: vishnu        
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16all
#                tag: master
#         triggeredBy:
#           steps:
#             - test3
#         execution:
#           onExecute:
#             - echo "test4"
#             - echo "NameF=$NameF"
#             - echo "NameL=$NameL"
