resources:
  - name: test
    type: gitRepo
    repoPath: vijayreddy1991/resourcebashpipeline
    configuration:
      integrationName: github_vijay
      branches:
        only: master
    version:
      sha: master

  - name: keys
    type: gitRepo
    repoPath: vijayreddy1991/secretkeys
    configuration:
      integrationName: github_vijay
      branches:
        only: master
    version:
      sha: master

pipelines:
  - name: pipe_vijay
    steps:
      - name: u16_node
        type: bash
        setup:
          runtime:            
            type: image
            image:
              auto:
                language: nodejs
                versions: 
                  - 10.15.3
              custom:
                name: drydock/c7node
                tag: master
                options: ""
        requires:
          resources:
            - test 
          integrations:
            - vijay_slack
            
        triggeredBy:
          resources:
            - test
            - keys
        execution:
          onStart:
            - printenv
          onExecute:
            - bump_semver v1.0.0 major
            - compare_git --resource test --commit-range HEAD~2..HEAD
            - printenv
#             - compare_git --commit-range 968cc732f0194516303157a09a3b245e86b8a408..master --path $STEP_DEPENDENCY_STATE_DIR/resources/test
#             - node --version 
#             - update_commit_status test --status success --message "updated u16node" --context $STEP_NAME
            - retry_command node --version
            - pushd $res_test_resourcePath 
            - read_json secret.json "TOP_SECRET_CONFIDENTIAL_FORMULA"
            - popd
            - pushd $res_keys_resourcePath
            - echo $res_keys_resourcePath
            - openssl genrsa -out key.pem 1024 
            - openssl rsa -in key.pem -text -noout
            - openssl rsa -in key.pem -pubout -out pub.pem 
            - openssl rsa -in pub.pem -pubin -text -noout
            - encrypt_file keys.txt --key pub.pem
            - cat encrypted
            - decrypt_file encrypted --key key.pem
            - popd
            - pushd $res_test_resourcePath 
            - cache_files old.env my_file
            - restore_cache my_file old.env
            - add_run_variable vijay=kumar
            - printenv
            - echo $vijay
            - send_notification vijay_slack 
            
#       - name: u18_node
#         type: bash
#         setup:
#           runtime:            
#             type: image
#             image:
#               auto:
#                 language: nodejs
#                 versions: 
#                   - 10.15.3
#               custom:
#                 name: drydock/u18node
#                 tag: master
#                 options: ""
#         triggeredBy:
#           resources:
#             - test
#           steps:
#             - u16_node
#         execution:
#           onStart:
#             - printenv
#           onExecute:
#             - echo "vijay" 
#             - bump_semver v1.0.0 minor
#             - compare_git --resource test
#             - printenv
#             - compare_git --commit-range 968cc732f0194516303157a09a3b245e86b8a408..master --path $STEP_DEPENDENCY_STATE_DIR/resources/test
#             - switch_env nodejs 8.16.0
#             - retry_command node --version
#             - pushd $res_test_resourcePath 
#             - read_json secret.json "TOP_SECRET_CONFIDENTIAL_FORMULA"
#             - popd
#             - pushd $res_keys_resourcePath
#             - echo $res_keys_resourcePath
#             - openssl genrsa -out key.pem 1024 
#             - openssl rsa -in key.pem -text -noout
#             - openssl rsa -in key.pem -pubout -out pub.pem 
#             - openssl rsa -in pub.pem -pubin -text -noout
#             - encrypt_file keys.txt --key pub.pem
#             - cat encrypted
#             - decrypt_file encrypted --key key.pem
#             - popd
#             - pushd $res_test_resourcePath 
#             - restore_cache my_file old.env
            
            
#       - name: c7_node
#         type: bash
#         setup:
#           runtime:            
#             type: image
#             image:
#               auto:
#                 language: nodejs
#                 versions: 
#                   - 10.15.3
#               custom:
#                 name: drydock/c7node
#                 tag: master
#                 options: ""
#         triggeredBy:
#           resources:
#             - test        
#           steps:
#             - u18_node
#         execution:
#           onStart:
#             - printenv
#           onExecute:
#             - bump_semver v1.0.0 minor
#             - compare_git --resource test
#             - printenv
# #             - compare_git --commit-range 968cc732f0194516303157a09a3b245e86b8a408..master --path $STEP_DEPENDENCY_STATE_DIR/resources/test
#             - pushd $res_test_resourcePath 
#             - read_json secret.json "TOP_SECRET_CONFIDENTIAL_FORMULA"
#             - popd
#             - pushd $res_keys_resourcePath
#             - echo $res_keys_resourcePath
#             - openssl genrsa -out key.pem 1024 
#             - openssl rsa -in key.pem -text -noout
#             - openssl rsa -in key.pem -pubout -out pub.pem 
#             - openssl rsa -in pub.pem -pubin -text -noout
#             - encrypt_file keys.txt --key pub.pem
#             - cat encrypted
#             - decrypt_file encrypted --key key.pem
#             - popd
#             - pushd $res_test_resourcePath 
#             - restore_cache my_file old.env
            
#       - name: test1
#         type: bash
#         setup:
#           environmentVariables:
#             normal:
#              Number: 27         
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16node
#                tag: master
#         triggeredBy:
#            resources:
#               - test
#         execution:
#           onExecute:
#             - echo "hi"
#             - printenv
#             - add_run_variable vijay=kumar

#       - name: test2
#         type: bash   
#         triggeredBy:
#           steps:
#             - test1
#         execution:
#           onExecute:
#             - echo "test2"
#             - echo $vijay
#             - echo $Number

#       - name: test3
#         type: bash  
#         triggeredBy:
#           steps:
#             - test2
#         execution:
#           onExecute:
#             - echo "Test3"
#             - echo $vijay

#       - name: test4
#         type: bash 
#         triggeredBy:
#           steps:
#             - test3
#         execution:
#           onExecute:
#             - echo "test4"
#             - echo $FOO_STATE

#       - name: testbash1
#         type: bash
#         configuration:
#           affinityGroup: vijay@#$%^&*
# #           priority: 3
# #           timeoutSeconds: <job timeout limit>
#           nodePool: kermit_ubuntu_pool
#           chronological: false       
#         setup:
# #           environmentVariables:
# #             normal:
# #               vijay: kumar  
#           runtime:            
#             type: image
#             image:
#               auto:
#                 language: nodejs
#                 versions: 
#                   - 8.16.0
#               custom:
#                 name: drydock/c7node
#                 tag: master
#                 options: ""
#         triggeredBy:
#           resources:
#             - test
#         execution:
#           onStart:
#             - printenv
#           onExecute:
# #             - test "$vijay" == "kumar"
#             - printenv
#             - echo "vijay"
# #           onSuccess:
# # #             - test "$ENV1" == "value1"
# #               - printenv
# #           onFailure:
# #            - printenv
# #           onComplete: #always
# #             - test "$vijay" == "kumar"
# #             - printenv
# #           onCancel:
# #             - test "$ENV1" == "value1"
# #             - test "$SECURE_ENV" == "key"

#       - name: testbash2
#         type: bash
#         configuration:
#           affinityGroup: vijay@#$%^&*
#           priority: 2
# #           timeoutSeconds: <job timeout limit>
#           nodePool: kermit_ubuntu_pool
#           chronological: false
#         setup:
# #           environmentVariables:
# #             normal:
# #               ENV1: value1
# #               ENV2: value2
# #             encrypted:
# #               SECURE_ENV1: <encrypted secure>
# #               SECURE_ENV2: <encrypted secure>
#           runtime:            
#             type: image
#             image:
#               auto:
#                 language: nodejs
#                 versions: 
#                   - 10.15.3
#               custom:
#                 name: drydock/u16node
#                 tag: master
#                 options: ""
#         triggeredBy:
#           steps:
#             - testbash1
#         execution:
#           onStart:
#             - printenv
#           onExecute:
# #             - test "$vijay" == "kumar"
#             - printenv
#             - echo "vijay"
#           onSuccess:
# #             - test "$ENV1" == "value1"
# #               - printenv
# #           onFailure:
# #            - printenv
# #           onComplete: #always
# #             - test "$vijay" == "kumar"
# #             - printenv
# #           onCancel:
# #             - test "$ENV1" == "value1"
# #             - test "$SECURE_ENV" == "key"
            

#       - name: testbash3
#         type: bash
#         configuration:
#           affinityGroup: vijay@#$%^&*
#           priority: 1
# #           timeoutSeconds: <job timeout limit>
#           nodePool: kermit_ubuntu_pool
#           chronological: false        
#         setup:
# #           environmentVariables:
# #             normal:
# #               vijay: kumar  
#           runtime:            
#             type: image
#             image:
#               auto:
#                 language: nodejs
#                 versions: 
#                   - 8.16.0
#               custom:
#                 name: drydock/u16node
#                 tag: master
#                 options: ""
#         triggeredBy:
#           steps:
#             - testbash2
#         execution:
#           onStart:
#             - printenv
#           onExecute:
# #             - test "$vijay" == "kumar"
#             - printenv
#             - echo "vijay"
#           onSuccess:
# #             - test "$ENV1" == "value1"
#               - printenv
#           onFailure:
#            - printenv
#           onComplete: #always
# #             - test "$vijay" == "kumar"
#             - printenv
#           onCancel:
# #             - test "$ENV1" == "value1"
# #             - test "$SECURE_ENV" == "key"
# #               - printenv

#       - name: test1
#         type: bash
#         setup:
#           environmentVariables:
#             readOnly:
#               NameF: reddy
#               NameL: umar       
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16all
#                tag: master
#         triggeredBy:
#           resources:
#             - test
#         execution:
#           onExecute:
#             - echo "test1"
#             - echo "NameL=$NameL"
#             - echo "NameF=$NameF"

#       - name: test2
#         type: bash
#         setup:
#           environmentVariables:
#             readOnly:
#               NameF: ranjan
#               NameL: bindu        
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16all
#                tag: master
#         triggeredBy:
#           steps:
#             - test1
#         execution:
#           onExecute:
#             - echo "test2"
#             - echo "NameF=$NameF"
#             - echo "NameL=$NameL"

#       - name: test3
#         type: bash
#         setup:
#           environmentVariables:
#             readOnly:
#               NameF: barath
#               NameL: jatin     
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16all
#                tag: master
#         triggeredBy:
#           steps:
#             - test2
#         execution:
#           onExecute:
#             - echo "Test3"
#             - echo "NameF=$NameF"
#             - echo "NameL=$NameL"

#       - name: test4
#         type: bash
#         setup:
#           environmentVariables:
#             readOnly:
#               NameF: Chaitu
#               NameL: vishnu        
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16all
#                tag: master
#         triggeredBy:
#           steps:
#             - test3
#         execution:
#           onExecute:
#             - echo "test4"
#             - echo "NameF=$NameF"
#             - echo "NameL=$NameL"
